### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by aharpervc** [runkitdev/demokit#1]
```
$ npm install demokit -g
C:\Users\aharper\AppData\Roaming\npm\demokit -> C:\Users\aharper\AppData\Roaming\npm\node_modules\demokit\bin\demokit-cli.js

> demokit@3.0.0 postinstall C:\Users\aharper\AppData\Roaming\npm\node_modules\demokit
> node install.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aharper\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "demokit" "-g"
npm ERR! node v6.9.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! demokit@3.0.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the demokit@3.0.0 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the demokit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs demokit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls demokit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\users\aharper\workspace\demokit\npm-debug.log
```

Not much in the npm-debug.log, but here's the failure lines:

```
731 silly lifecycle demokit@3.0.0~postinstall: Args: [ '/d /s /c', 'node install.js' ]
732 silly lifecycle demokit@3.0.0~postinstall: Returned: code: 1  signal: null
733 info lifecycle demokit@3.0.0~postinstall: Failed to exec postinstall script
```

**Comment by rentzsch** [comment]
Sorry, there's a lot of macOS-specific dependancies.

Pull Requests welcome.

**Comment by pouwerkerk** [comment]
@aharpervc, great idea! We absolutely want to support Windows, but didn't get around to it before shipping this first version. There are two main places where we rely on macOS APIs: screen recording and simulating mouse movement. We plan on eventually supporting Windows, but of course, we're happy to facilitate working on this if there's a strong demand for it earlier.
