### ISSUE TITLE
TypeError: demo is not a function

### ISSUE THREAD

**Issue by hemanth** [runkitdev/demokit#10]
```
$ demokit 
TypeError: demo is not a function
    at EventEmitter.<anonymous> (/Users/hemanth/.yarn-cache/.global/node_modules/demokit/electron/demokit-run.js:66:19)
    at next (<anonymous>)
    at step (/Users/hemanth/.yarn-cache/.global/node_modules/demokit/electron/demokit-run.js:5:191)
    at /Users/hemanth/.yarn-cache/.global/node_modules/demokit/electron/demokit-run.js:5:437
    at EventEmitter.<anonymous> (/Users/hemanth/.yarn-cache/.global/node_modules/demokit/electron/demokit-run.js:5:99)
    at EventEmitter.on (/Users/hemanth/.yarn-cache/.global/node_modules/demokit/electron/demokit-run.js:33:5)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at WebContents.<anonymous> (/Users/hemanth/.yarn-cache/.global/node_modules/demokit/electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:210:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

It's failing at [this](https://github.com/runkitdev/demokit/blob/master/electron/demokit-run.js#L64) line. 

On `v6.9.1`:

```js
> require('/Users/hhegadehallimadh/.yarn-cache/.global/node_modules/demokit/electron/demokit-run.js')
/Users/hhegadehallimadh/.yarn-cache/.global/node_modules/demokit/electron/demokit-run.js:33
    on("ready", async function(event)
                ^^^^^
SyntaxError: missing ) after argument list
```

**Comment by tolmasky** [comment]
Demokit automatically runs it through babel, there might be some issue from doing it through yarn (haven't tried installing it through yarn yet). Also, the path to the demokit script needs to be passed (I think calling it without that won't work).

**Comment by hemanth** [comment]
```sh
demokit new meow
cd meow
demokit 
```
Same with ^

**Comment by tolmasky** [comment]
Right I'm saying you have to pass the path in. If you're in meow you would do demokit index.js.

**Comment by hemanth** [comment]
`demokit .` works fine 👍

**Comment by tolmasky** [comment]
Cool I'll make it so passing in nothing uses the current directory

**Comment by hemanth** [comment]
It's on me!
