### ISSUE TITLE
Failing to install on v6.6.0

### ISSUE THREAD

**Issue by hemanth** [runkitdev/demokit#8]
```
$ demokit 
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/hemanth/.nvm/versions/node/v6.6.0/lib/node_modules/demokit/electron/node_modules/electron/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/Users/hemanth/.nvm/versions/node/v6.6.0/lib/node_modules/demokit/bin/demokit-cli.js:23:61)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
```

`OSX`

**Comment by tolmasky** [comment]
Do you mind trying it on 6.9.1? I was on 6.5 and it works, and just upgraded to 6.9.1 and it also worked.

Also, could you possibly tell me the contents of the "/Users/hemanth/.nvm/versions/node/v6.6.0/lib/node_modules/demokit/electron/node_modules/electron/" folder?

**Comment by hemanth** [comment]
Yup, working fine on `6.9.1` should we still keep this open?
